name: Social_Distancing_App
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3

  #plugin required to be installed
  beacon_broadcast: ^0.2.1
  snowm_scanner: ^0.5.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
